$paths = @(
    "CLAUDE.md",
    "README.md",
    "main.tex",
    "referencias.bib",
    ".claude\agents",
    ".claude\commands",
    ".claude\skills",
    ".claude\agents\reformas-analyst.md",
    ".claude\commands\analizar-lote.md",
    ".claude\commands\buscar-fuente.md",
    "00_instrucciones",
    "00_instrucciones\criterios_fuentes.md",
    "00_instrucciones\criterios_reformas_legislativas.md",
    "00_instrucciones\estructura_capitulos.md",
    "00_instrucciones\flujo_trabajo.md",
    "01_fuentes_pdf_originales\normativa",
    "01_fuentes_pdf_originales\jurisprudencia",
    "01_fuentes_pdf_originales\doctrina",
    "01_fuentes_pdf_originales\institucional",
    "01_fuentes_pdf_originales\internacional",
    "01_fuentes_pdf_originales\prensa",
    "01_fuentes_pdf_originales\reformas_legislativas",
    "02_fuentes_md\normativa",
    "02_fuentes_md\jurisprudencia",
    "02_fuentes_md\doctrina",
    "02_fuentes_md\institucional",
    "02_fuentes_md\internacional",
    "02_fuentes_md\prensa",
    "02_fuentes_md\reformas_legislativas",
    "03_fichas\fichas_normativas",
    "03_fichas\fichas_jurisprudenciales",
    "03_fichas\fichas_doctrina",
    "03_fichas\fichas_institucionales",
    "03_fichas\fichas_internacionales",
    "03_fichas\fichas_prensa",
    "03_fichas\fichas_reformas_legislativas",
    "04_matrices\matriz_fuentes.md",
    "04_matrices\matriz_normativa.md",
    "04_matrices\matriz_jurisprudencial.md",
    "04_matrices\matriz_doctrina.md",
    "04_matrices\matriz_institucional.md",
    "04_matrices\matriz_internacional.md",
    "04_matrices\matriz_prensa_contextual.md",
    "04_matrices\matriz_reformas_legislativas.md",
    "04_matrices\matriz_cdiu.md",
    "04_matrices\matriz_compatibilidad_constitucional_ambiental.md",
    "05_capitulos\preliminares.tex",
    "05_capitulos\introduccion.tex",
    "05_capitulos\capitulo_1_problema.tex",
    "05_capitulos\capitulo_2_marco_referencial.tex",
    "05_capitulos\capitulo_3_metodologia.tex",
    "05_capitulos\capitulo_4_propuesta.tex",
    "05_capitulos\conclusiones.tex",
    "05_capitulos\recomendaciones.tex",
    "06_tablas\tabla_cdiu.tex",
    "06_tablas\matriz_reformas_legislativas.tex",
    "06_tablas\matriz_normativa.tex",
    "06_tablas\matriz_jurisprudencial.tex",
    "06_tablas\matriz_compatibilidad.tex",
    "07_anexos\anexos.tex",
    "08_build",
    "scripts"
)

foreach ($path in $paths) {
    if (Test-Path $path) {
        Write-Host "[OK] $path" -ForegroundColor Green
    } else {
        Write-Host "[FALTA] $path" -ForegroundColor Red
    }
}
